# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
import matplotlib.pyplot as plt
import pandas as pd

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
df = pd.read_excel('Folds5x2_pp.xlsx') # Read the dataframe from the excel file
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0) # 20% of data will be used for testing

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = keras.Sequential()# Sequential is a linear stack of layers in the neural network model (in this case, a simple feedforward network)

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim=4)) # Dense is a layer in the neural network model

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim=4)) # Dense is a layer in the neural network model (in this case, a simple feedforward network)

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # Dense is a layer in the neural network model and the output layer has a single neuron with a sigmoid activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer='adam', loss='mean_squared_error') # Compile the model with the optimizer and loss function

### Training the ANN model on the Training set

In [12]:
ann.fit(x_train, y_train, batch_size=32, epochs=100) # Train the model with the training data

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 205774.5938
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6562
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.5312
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6719
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6406
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.5938
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.7812
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6719
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6094
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.7344
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 205774.6562
Epoch 12/100
240/240 [===================

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(x_test) # Predict the output of the test data
np.set_printoptions(precision=2) # Set the precision of the output to 2 decimal places (for the sake of readability)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)) # Print the predicted output and the actual output of the test data